name: PR Build

on:
  pull_request:
    branches:
    - master
    
jobs:
    build:
      name: Build
      env:
        NUPKG_MAJOR: 0.3
      runs-on: macos-latest
      steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.100
      - name: Build and Pack - CI
        run: |
          VERSION=$NUPKG_MAJOR-ci$GITHUB_RUN_ID
          mkdir ./output
          mkdir ./artifacts
          dotnet build --configuration Release ./Resizetizer.NT/Resizetizer.NT.csproj
          dotnet pack --output ./artifacts -p:PackageVersion=$VERSION -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --configuration Release ./Resizetizer.NT/Resizetizer.NT.csproj
      - name: Run Tests
        run: dotnet test --configuration Release ./Resizetizer.NT.Tests/Resizetizer.NT.Tests.csproj
